### ISSUE TITLE
[Bug]:  Valhelsia Core & Optifine Issue

### ISSUE THREAD

**Issue by penturt** [stal111/Valhelsia-Structures#147]
### Describe the issue

the latest version of [Forge] Valhelsia Core - 0.4.0 and OptiFine_1.18.2_HD_U_H7 seem to be incompatible, had to go back tovalhelsia_core-1.18.2-0.3.1 so that i could also use Optifine.

### Minecraft Version

1.18.2 (Default)

### Mods Version

- Forge: 1.18.2 - 40.1.68
- Valhelsia Structures: valhelsia_structures-forge-1.18.2-0.1.0
- Valhelsia Core: [Forge] Valhelsia Core - 0.4.0 

### Log

```shell
https://gist.github.com/penturt/e181c55120b09bcabf6c73bbe2620f59
```

**Comment by YeraX7** [comment]
I have the same issue, any solution?

**Comment by codewithbjim** [comment]
Same Issue with me.

**Comment by YeraX7** [comment]
Hey, I have a solution.
Just replace the version of Valhesia Core to the 0.3.1

**Comment by Lucreeper74** [comment]
> Hey, I have a solution. Just replace the version of Valhesia Core to the 0.3.1

Thx u so much ! It's working for me ! Just downgrade Valhelsia Core and don't forget to downgrade forge to 40.1.57 (Because higher Optifine crash)

**Comment by Asfhen** [comment]
Same error happens with the 0.4.0 version for 1.19.2, you can see the crash report here: https://gist.github.com/Asfhen/08f1507717a29c47cb18a3f2b2ee4b99

**Comment by joejoe135791** [comment]
I appear to be running into the same issue

**Comment by Spaceflyer914** [comment]
I think I have the same issue. When I put OptiFine 1.19 into my mods folder the game crashes when I try to launch it and I can't even get to the main menu. The crash report says that there is an error with valhelsia core 1.19. When I try to use Valhalla structures it also crashes, but it could be because I'm playing on 1.19.2 and Valhalla structures is for 1.18. How would we ask the developers to fix this, or if we don't do that then what do we do in this situation? This is my first time reporting a bug.

**Comment by Spaceflyer914** [comment]
I downgraded Forge and Valhalla core so that they still work with 1.19 but it's still crashed with OptiFine. I guess they're incompatible for now?

**Comment by Spaceflyer914** [comment]
How do I know when this is fixed?

**Comment by Aetrnl94** [comment]
Any idea as to when/if there will be a fix for those of us who use Optifine? I'd love to play with the mods in this group but I can't sacrifice Optifine to do it. Thanks!

**Comment by Vaelzan** [comment]
> Any idea as to when/if there will be a fix for those of us who use Optifine? I'd love to play with the mods in this group but I can't sacrifice Optifine to do it. Thanks!

You would have to ask the OptiFine developer. We can't fix it on our end.

**Comment by acorsicanfrog** [comment]
How a mod that adds structures can conflict with Optifine? I'm legit baffled LOL

**Comment by Vaelzan** [comment]
> How a mod that adds structures can conflict with Optifine? I'm legit baffled LOL

Well, when OptiFine removes some Minecraft code related to 3D models, and a mod adds blocks with custom 3D models that rely on that code actually existing in the game... that's a problem. It's not like we only add structures, otherwise there'd be no reason to make it a mod, it could just be a datapack.
