### ISSUE TITLE
[Bug]: this is a feature request

### ISSUE THREAD

**Issue by Developer2704** [stal111/Valhelsia-Structures#162]
### Describe the issue

I think there should be a non ruined version of the tower and a dowsed brazier. Mabey some sort of not ruined but abandoned castle.

### Minecraft Version

1.19.2 (Default)

### Mods Version

- Forge: all
- Valhelsia Structures: all
- Valhelsia Core: all

### Log

```shell
This is a feature request. There should also be a template for feature requests.
```

**Comment by Vaelzan** [comment]
Braziers already have an unlit variant - right-click them with a shovel the same way you would a campfire (I didn't know about this until just now either... oops).

There'll quite likely be new variants of existing structures added in the future, just like we recently added some new house types (to make use of deepslate and moss after Minecraft 1.17). I can't give any specifics yet though, you'll have to wait and see.

There's no template for feature requests because this is purely used to track issues. We have a separate system for organising upcoming features, to avoid spoilers.

If you have any more suggestions, please use Discord or Reddit rather than here.
