### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by LeqitDev** [stal111/Valhelsia-Structures#30]
I tried to install and startup a modded server on my RaspberryPi 4 8Gb but every time it crashed. I haved installed the beta version of the 64-Bit ARM Raspberry Pi OS (based on Debian) to access more then 2 GB JVM RAM.
The Debug Log:
[debug.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/5213007/debug.log)

**Comment by Vaelzan** [comment]
The crash has nothing to do with Valhelsia Structures, so you're asking in the wrong place. This is NOT the place to get support for the Valhelsia pack, which is through Discord.

However, I can tell you that it's because you're running Java 11 and modded Minecraft is intended to be run on Java 8 (or OpenJDK 8).

**Comment by LeqitDev** [comment]
Srry I'm dumb didn't see it
