### ISSUE TITLE
Adding modifications for 1.16.1 structures

### ISSUE THREAD

**Issue by Elasky** [stal111/Valhelsia-Structures#31]
Spent sometime with trying to change the config file to allow more generation of the structures in the over world both in SP and server sessions without any changes. I even went down to just the forge load along with the structures and all the changes that I attempted to do with the minecraft 1.16.1 version where ignored.

This same config used on a 1.15.2 sp and server generated the multiple structures without any problems.

I am not sure if this is a minecraft 1.16.1 problem or the config file being actually used.

**Comment by sweetbabyj3** [comment]
I've experienced the same issue on 1.16.3. The config file seems to be ignored completely. If I make edits and reload the game, I never get the notepad message "File has changed, would you like to reload". I've changed all settings to max & min values but structures are always spawned in the same places. Hope this helps, the mod is great otherwise. 

Some world gen mods I'm also using :
BOP
Quark
Waystones
Repurposed Structures
Yung's Better Caves & Mineshafts
Dungeons Plus
Dungeon Crawl

**Comment by Vaelzan** [comment]
Please be aware that in the 1.16 versions of the mod you will need to modify the config file that is inside the world / save folder, serverconfigs subfolder. Modifying the one in the regular config folder won't work.

We're changing the way that configs work next release to prevent confusion (there won't be duplicate configs then), but the above is the process to use for now in any current 1.16 version.

**Comment by sweetbabyj3** [comment]
My mistake, I've been on 1.12 for years. Hard to get used to all the changes, but thank you for the clarification. Can't wait to try it when I get home!
