### ISSUE TITLE
Minecraft looks grainy after installing Valhesia Structures 

### ISSUE THREAD

**Issue by ghost** [stal111/Valhelsia-Structures#32]
Im using a small amount of mods chosen by me because the modpacks are so insanely heavy and complicated. I have installed the following mods: Biomes OPlenty, Falling tree, journey map, Optifine, Terraforged and everything was fine until i installed valhesia structures. Only when i load the game with this mod installed minecraft looks really grainy and horrible (looking at a far forest, for example)

**Comment by Vaelzan** [comment]
This is a known issue with mipmap settings in the 1.14.4 and 1.15.2 versions. It's fixed in 1.16.1 but we haven't had a chance to backport the fix to the other versions yet. I'll try to get the fixed version out at some point.

If you report issues to any mod on GitHub in the future, please include the mod and Forge version, as developers need that information to diagnose issues. I was just lucky that I had already encountered this issue in the past.

**Comment by stal111** [comment]
1.14 and 1.15 most likely wont receive any more updates, thus im closing the issue.
