### ISSUE TITLE
dungeon crawl

### ISSUE THREAD

**Issue by pwghost** [stal111/Valhelsia-Structures#34]
hi, i have dungeon crawl and valhelsia structures running on 1.16.1 and when i use the locate command for valhelsia structures the dungeon crawler worker starts generating structures but no structures of valhelsia are generated.

**Comment by pwghost** [comment]
i narrowed it down to the /locate valhelsia.dungeon command 
then the screenshot is happening in the console all other commands seem to work
 
![image](https://user-images.githubusercontent.com/52128197/95082086-d50ee780-071a-11eb-90c2-da5d0b68ce86.png)

**Comment by Vaelzan** [comment]
The Dungeon Crawl mod generating dungeons when you run the locate command is pretty problematic, since it will generate a potentially massive amount after running the command. Please report that to them, showing them the screenshot above.

For now, until they fix it, a workaround might be to use Forge's inbuilt pre-generation command first, before using /locate. That way when you use /locate the dungeons are already generated, and it will simply help you find the structure that you're looking for.
