### ISSUE TITLE
Small Dungeon structure spawns weird, filled with stone and water . Is it not filled with air blocks?

### ISSUE THREAD

**Issue by BugmanBugman** [stal111/Valhelsia-Structures#38]
![2020-10-14_16 20 29](https://user-images.githubusercontent.com/40730042/96047667-17cb7080-0e3b-11eb-86de-c96cfab31a86.png)
![2020-10-14_16 20 32](https://user-images.githubusercontent.com/40730042/96047669-18640700-0e3b-11eb-9f21-38145d668ba0.png)
![2020-10-14_16 20 37](https://user-images.githubusercontent.com/40730042/96047671-19953400-0e3b-11eb-8603-2a702f140940.png)
![2020-10-14_16 20 55](https://user-images.githubusercontent.com/40730042/96047675-1ac66100-0e3b-11eb-8a71-0b6661b86442.png)

**Comment by BugmanBugman** [comment]
![2020-10-14_16 46 38](https://user-images.githubusercontent.com/40730042/96049465-ab9e3c00-0e3d-11eb-8958-68734a60ef79.png)
![2020-10-14_16 46 36](https://user-images.githubusercontent.com/40730042/96049470-accf6900-0e3d-11eb-97c0-116afcdde6b7.png)
![2020-10-14_16 46 29](https://user-images.githubusercontent.com/40730042/96049474-ad67ff80-0e3d-11eb-8c0a-faccc0d1efc9.png)
Nvm, I don't think it's YUNG's. The small dungeon structure seems borked in general. I tested it without YUNGs and it was still filled with stone and water.

**Comment by Vaelzan** [comment]
Please let us know which version of the mod you are using, which Forge version, and a list of other mods installed (with versions). I can't begin to troubleshoot when I don't even know if you're playing Minecraft 1.14.4, 1.15.2, 1.16.1, or 1.16.3, all of which have that dungeon.

**Comment by BugmanBugman** [comment]
My bad, it’s 1.16.3 and the forge version was 34.1.23

I can’t get a comprehensive list of my mods rn, but when I get on tmrw I can do some binary searching to see if it’s a mod compat issue

**Comment by ScottKillen** [comment]
Your logs contain a list of your mods and a lot of other helpful information. Please reply and drag and drop your log file into the reply.

**Comment by BugmanBugman** [comment]
[debug.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/5404325/debug.log)
[latest.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/5404326/latest.log)
Not sure if that would help, I just tested the mod by itself and the small dungeon structure was still filled with stone and water. It seems to be borked naturally, maybe it wasn't saved right?
![2020-10-19_14 47 52](https://user-images.githubusercontent.com/40730042/96504481-58036800-121a-11eb-9af2-eaf85c2aeb9a.png)
![2020-10-19_14 48 02](https://user-images.githubusercontent.com/40730042/96504483-589bfe80-121a-11eb-94e6-2a75b98e113d.png)
![2020-10-19_14 47 26](https://user-images.githubusercontent.com/40730042/96504484-59cd2b80-121a-11eb-8ab8-fd20ccb55d65.png)
![2020-10-19_14 47 32](https://user-images.githubusercontent.com/40730042/96504487-59cd2b80-121a-11eb-8408-13c6968b774d.png)
I don't believe the structure is supposed to look like this according to the trailer.

**Comment by TelepathicGrunt** [comment]
Yeah can confirm. 

My suspicion is that it is this method:

https://github.com/ValhelsiaTeam/Valhelsia-Structures/blob/86ccfe0970b8d2c2cde58b7cbc363a458048d165/src/main/java/com/stal111/valhelsia_structures/utils/JigsawHelper.java#L41

`JigsawPiece.func_242849_a` is the same as using "minecraft:legacy_single_pool_element" for template pool json files.
It's for pillager outposts and villages which are older jigsaw structures and are setup in a certain way. Now what I believe you should be doing just for the dungeon is `JigsawPiece.func_242861_b` as this is "minecraft:single_pool_element" for template pool json files.

Their is a slight difference in Air/Structure Void behavior I found and it has tripped me up too. So give `JigsawPiece.func_242861_b` a try with the dungeon as when I spawned the dungeon piece myself by Structure Blocks, it did replace the stone with air properly which is why I thought about this weird edge case thing.

**Comment by Vaelzan** [comment]
@TelepathicGrunt Thanks for that insight. I've let the 1.16.3 developer know. Much appreciated. :)

**Comment by Khytwel** [comment]
Problem fixed in the latest version (16.0.5).
