### ISSUE TITLE
With Valhelsia installed i CANNOT join ANY servers

### ISSUE THREAD

**Issue by Eclipse-Ilx** [stal111/Valhelsia-Structures#50]
Single player theres no issue mods works 100% fine

However i cannot join any server with the mod installed wether the server has the mod or not

I have tested this with only Valhelsia Structures 16.0.5 installed still same issue

The error i get says:

Internal Exception: Java.lang.ClassCastException: net.minecraft.world.Biome$category cannot be cast to java.lang.String

**Comment by Vaelzan** [comment]
That error happens when trying to connect to a vanilla server, and I've only *ever* seen that happen in that situation. Usually it is because somebody has run the wrong jar file when starting up a server (since Forge servers include the full vanilla Minecraft server files, it's easy to run the wrong thing).
