### ISSUE TITLE
The color of the grass block does not change with the biome

### ISSUE THREAD

**Issue by LTCatt** [stal111/Valhelsia-Structures#72]
![image](https://user-images.githubusercontent.com/40348278/119230574-6c606800-bb4f-11eb-9357-a099e3655053.png)

Environment:
valhelsia_core-16.0.8
valhelsia_structures-1.16.5-0.1.1
OptiFine_1.16.5_HD_U_G8_pre12

**Comment by Vaelzan** [comment]
This is caused by an interaction with the Greener Grass feature from Quark, and we have submitted code to Quark to get Valhelsia Structures supported (since it needs to be done on their end), but it will only be fixed after they accept the pull request + release an update, so we're waiting on that now. If it isn't accepted in the near future, you should submit an issue report on Quark's tracker linking to the PR: https://github.com/Vazkii/Quark/pull/3205
