### ISSUE TITLE
Quark Clash

### ISSUE THREAD

**Issue by Foozey** [stal111/Valhelsia-Structures#75]
Both this mod and Quark add Paper Walls which are basically identical. I think it's fairly safe to assume that the majority of people using this mod will also have Quark installed. I would suggest adding some logic that detects if Quark is installed, and if so, prevent the Paper Wall in this mod from being registered. There's also obviously some compatibility issues with other mods as well, but I wouldn't expect the development to consider those since they're nowhere near the scale of Quark in terms of popularity.

**Comment by Vaelzan** [comment]
Mods regularly add similar blocks to those added by other mods. This isn't an issue. There's no recipe conflict since we use a different recipe, and there are no bugs caused by having both there since they're independent from each other.

It would cause a performance hit for us (and a non-trivial amount of work) to replace any given block, since we would need to run a process on each structure generated to swap out the blocks, and also ensure that they have the correct state. It simply isn't practical to do, nor should we have to.

Even in cases where there are recipe conflicts or it is preferable to not see similar blocks in JEI (or other similar issues of preference), that is a task for a mod pack creator to handle (using something like KubeJS or CraftTweaker), not either of the mod developers.
