### ISSUE TITLE
 Unknown structure start: valhelsia_structures:small_dungeon

### ISSUE THREAD

**Issue by Dubslash** [stal111/Valhelsia-Structures#77]
After Server Update from 3.3.1 to 3.3.3 the Server log is spammed with:
`[Server thread/ERROR] [minecraft/ChunkSerializer]: Unknown structure start: valhelsia_structures:small_dungeon
`

Minecraft Version: 1.16.5
Forge Version: 36.1.25
Valhelsia Version: 3.3.3
V. Structures Version: 0.1.2

**Comment by KajesLorian** [comment]
I have the same thing. Spam like crazy.

Minecraft 1.16.5
Forge 36.1.15
Vahelsia Structures 0.1.2

**Comment by rbaker87** [comment]
Same issue here. Server was updated from 3.3.2a to 3.3.3.  

Minecraft version 1.16.5
Forge version 36.1.25
Valhelsia version 3.3.3
Valhelsia Structures version 0.1.2

**Comment by chosti-factor** [comment]
Same issue.

Minecraft 1.16.5
Forge 36.1.0
Vahelsia Structures 0.1.2

**Comment by Vaelzan** [comment]
Anybody updating from an old world (from before Valhelsia Structures 0.1.1) to a new one will have this issue, unfortunately. It's a side effect of how Forge deals with removing structures from existing worlds (the small dungeon was removed + replaced with a different dungeon). We can most likely add a workaround for the next release though to avoid this, since it's easy enough to just add a "dummy" dungeon to prevent the log spam.

**Comment by TelepathicGrunt** [comment]
It's actually pretty easy to add log suppression for any structure or structure piece that you removed. First make a class with the same annotation, extends AbstractFilter, and implements the LogEvent method. In there, do matching for your mod's mod id for the "Unknown structure piece" and ""Unknown structure start" messages and do `return Result.DENY;` if so.  https://github.com/TelepathicGrunt/RepurposedStructures/blob/3075bcb64aed4819d3f0c800c05bdfceb29ff057/src/main/java/com/telepathicgrunt/repurposedstructures/utils/LogSpamFiltering.java#L62

Then add the class to the logger in mod init
https://github.com/TelepathicGrunt/RepurposedStructures/blob/3075bcb64aed4819d3f0c800c05bdfceb29ff057/src/main/java/com/telepathicgrunt/repurposedstructures/RepurposedStructures.java#L138

Hope this helps! It is a better solution than doing dummy structures or pieces so that they don't show up still in /locate and Forge already makes the world safe for structure remove. Just the logspam needs to be suppressed.

**Comment by stal111** [comment]
A log filter had been implemented in release 0.1.3.
