### ISSUE TITLE
Structure Generation Issue

### ISSUE THREAD

**Issue by rubinaito** [stal111/Valhelsia-Structures#80]
Hello!
I've been working on a modpack for my personal server. It's using Minecraft 1.16.5 and Forge 36.1.4
At the time of writing I have attempted multiple times to find the Valhelsia Structures, both manually as well as using the /locate command. However, using /locate specifically with the Valhelsia Structures crashed my server and froze the personal world I was using for testing. 

The problem occurs as follows (recreated on the server):
1. OP logs in, uses /locate valhelsia_structures:castle (or any of the structures)
2. The server doesn't send back a location, like it would with any other structure (tested this, the /locate command works fine with everything else)
3. All entities appear to freeze in place, and the player is unable to interact with them. However, the player is able to move around and break blocks; in this instance, it was also raining, and the rain didn't freeze either.
4. Eventually the player is kicked from the server with the 'Timed Out' message
5. The server appears to run fine afterwards until the player attempts to rejoin, in which the server crashes.

The console log lists the following in regards to the crash:

"A single server tick took 60.00 seconds."
"Considering it to be crashed, server will forcibly shutdown."
"Preparing crash report with UUID [insert code here]"
"Server shut down (running)"
"Restarting crashed server in 10 seconds"
"Looks like a crash, check the server console. Return value: 1"

As far as I can tell from the logs, the /locate command is what causes the crash specifically, and there aren't any structures generating. I can add both modpack lists if needed to see if it's a compatibility issue but seeing that another person has a similar issue, it might be a problem with the mod itself.

- Rubin

**Comment by Vaelzan** [comment]
That behaviour is actually (unfortunately) normal for the built-in `/locate` command if the command can't find any structures, it searches a larger and larger area until the ticks take so long the watchdog crashes the server. It does eventually give up, but in a heavily modded pack it can't reach that point because of the extended tick time.

The main issue is why it wouldn't be finding any of the structures. Are you in a normal Minecraft Overworld? Do you have any mods that overhaul world generation or heavily customise biomes? Basically, my guess is that there's a compatibility issue with another mod preventing the structures from generating (or causing them to generate incredibly far apart), and thus `/locate` being unable to find them (and displaying that behaviour).

A full mod list would help, as well as a short sub-list of any world generation or biome mods. I might be able to narrow it down from there.

**Comment by rubinaito** [comment]
> That behaviour is actually (unfortunately) normal for the built-in `/locate` command if the command can't find any structures, it searches a larger and larger area until the ticks take so long the watchdog crashes the server. It does eventually give up, but in a heavily modded pack it can't reach that point because of the extended tick time.
> 
> The main issue is why it wouldn't be finding any of the structures. Are you in a normal Minecraft Overworld? Do you have any mods that overhaul world generation or heavily customise biomes? Basically, my guess is that there's a compatibility issue with another mod preventing the structures from generating (or causing them to generate incredibly far apart), and thus `/locate` being unable to find them (and displaying that behaviour).
> 
> A full mod list would help, as well as a short sub-list of any world generation or biome mods. I might be able to narrow it down from there.

I suspect that the incompatible mods are the 1.17 backport mod I'm using (Caves & Cliffs Backport), and the Extended Caves mod seeing as those are the two world generation mods that both modpacks share.

**Comment by Morabert** [comment]
> 
> 
> That behaviour is actually (unfortunately) normal for the built-in `/locate` command if the command can't find any structures, it searches a larger and larger area until the ticks take so long the watchdog crashes the server. It does eventually give up, but in a heavily modded pack it can't reach that point because of the extended tick time.
> 
> The main issue is why it wouldn't be finding any of the structures. Are you in a normal Minecraft Overworld? Do you have any mods that overhaul world generation or heavily customise biomes? Basically, my guess is that there's a compatibility issue with another mod preventing the structures from generating (or causing them to generate incredibly far apart), and thus `/locate` being unable to find them (and displaying that behaviour).
> 
> A full mod list would help, as well as a short sub-list of any world generation or biome mods. I might be able to narrow it down from there.

Couldn't you make the mod configurable so that it would be able to generate with modded biomes & other structure generation? Because it seems the structure generation issue is unique to Valhesia as other structure generation mods don't have this issue. I've noticed that even in worlds where Valhesia structures were generating from the outset if I install other structure generation mods Valhesia Structures stops generating in new chunks.

**Comment by Vaelzan** [comment]
@Morabert It does work alongside most modded biomes and structures. We have quite a few of both in the Valhelsia modpacks and haven't had any issues with structure generation. If you're having problems with a specific mod, then we need to know which mod is conflicting in order to do anything about it.

**Comment by Morabert** [comment]
When Dungeons Arise, Extractures, & Immersive Weapons all produce this result.

**Comment by Morabert** [comment]
I was looking through the level.dat and Valhesia Structures isn't in the biome structure string:
![Valhesia no](https://user-images.githubusercontent.com/36409264/128295629-dfec8621-599b-4623-9515-c20c4754f683.JPG)
![see no Valhesia](https://user-images.githubusercontent.com/36409264/128295634-6da8a6fc-6776-4d96-9385-c66f4eca0c40.JPG)

**Comment by stal111** [comment]
I tested with all the mods mentioned in the thread and they all worked together. Are you sure that this issue still happens with the newest version of Valhelsia Structures?

**Comment by Morabert** [comment]
I'm on a new installation with up-to-date versions of the mods & it's still getting overwritten/choked out in terms of structure generation

**Comment by Morabert** [comment]
> 
> 
> I tested with all the mods mentioned in the thread and they all worked together. Are you sure that this issue still happens with the newest version of Valhelsia Structures?

Maybe the fact that nearly half of the open issues are structure generation incompatibility issues with just about every other mod that generates structures is a context clue that the issue is _fundamental and endemic_ to the Valhesia Structures mod? And as such, spending time and effort simply debunking our claims isn't really the best use of your valuable skills & resources?

**Comment by Vaelzan** [comment]
> > I tested with all the mods mentioned in the thread and they all worked together. Are you sure that this issue still happens with the newest version of Valhelsia Structures?
> 
> Maybe the fact that nearly half of the open issues are structure generation incompatibility issues with just about every other mod that generates structures is a context clue that the issue is _fundamental and endemic_ to the Valhesia Structures mod? And as such, spending time and effort simply debunking our claims isn't really the best use of your valuable skills & resources?

Do you really think that Stal is testing with the mods you mentioned purely to try to debunk your claims? Maybe don't make such utterly ridiculous claims in the future when you're trying to get an issue resolved.

Testing two mods alongside each other is what almost every developer would do when trying to figure out potential incompatibility, as the first step is to be able to reproduce the issue consistently. He tested them alongside Valhelsia Structures, and it worked completely fine (I've seen the screenshots of them working together), thus why he asked a perfectly legitimate follow-up question. Given that, it's quite likely that there's a third mod interfering in some way, but you didn't provide a full mod list.

If the only reason for your hostile comment is that it has been about a month since the last comment, please be aware that not only has Stal been on vacation for a while, he's also working on several other projects, and these mods are created in our free time. Things take time to resolve, especially if we don't even know which other mods are interfering with things.

**Comment by Morabert** [comment]
No, I think even spending time on this line of questioning & isolation is a waste of everyone's time & energy. That they can't duplicate the issue doesn't mean anything & isolating how I've had the same issue over half a dozen world generations with nearly as many different mod configs is not a good use of anyone's time. Half the open tickets _right here_ are about WorldGen/StructureSpawn and sound inductive reasoning heavily points to an endemic issue Re; how Structure/BiomeIDs are handled/presented/listed by Valhesia Structures and how that's interfacing either with other mods or the Forge API or both. No one's calling anyone a liar, We're saying querying for further evidence from us instead of relying upon pattern recognition is a bad protocol
![FammForRealFamm](https://user-images.githubusercontent.com/36409264/133263044-984936be-660f-4e5c-804f-013244d56974.jpg)

**Comment by Khytwel** [comment]
Why did you highlighted issues when some of them are either fixed or not related to your problem? 

Otherwise, you can also save your energy to send us an export of your modpack to finally test it and see what doesn't work.

**Comment by Morabert** [comment]
read the thread & check the timestamps, you're deadposting.

**Comment by Khytwel** [comment]
Well, I saw your answer and I do not intend to waste my time with a more than disrespectful and uneducated person.
