### ISSUE TITLE
Crash when encountering structures during generation

### ISSUE THREAD

**Issue by NielsPilgaard** [stal111/Valhelsia-Structures#82]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2436
Also reported here: https://github.com/TerraForged/tracker/issues/128

While pre-generating our server world it encountered some kind of Tetra and Valhelsia structure which causes a hard crash as soon as it loaded those chunks. I haven't yet tested if manually going into those chunks will have the same effect.

### Versions
- Forge-1.16.5-36.1.31
- valhelsia_structures-1.16.5-0.1.2
- TerraForged-1.16.5-0.2.10

**Comment by NielsPilgaard** [comment]
Response from TerraForged:

> Hi. It's propagating from feature [tetra:feature]. Looks like it's trying to place (or is maybe causing a block update on) one of Valhesia Structure's blocks (..valhelsia_structures.block.DungeonDoorBlock) during feature/structure generation, and part of that block's code is not safe to call within this part of chunk generation causing the ClassCastException which is blowing everything up.

Do you think this is something you could fix, or should I proceed to report this to Tetra? 😄

**Comment by Vaelzan** [comment]
Should be fixed in this commit: https://github.com/ValhelsiaTeam/Valhelsia-Structures/commit/71b8c7ec9dcfa442f7a69f14dfcc91439a46627e, but we can't really verify the fix since it's a very unique situation - it appears that it would only trigger with TerraForged (or a mod that does something very similar to what they do) when a feature overlaps an area on or near the dungeon door of our spawner dungeon in a way that causes the door to break, which is pretty rare.

Regardless, the change does also add additional safety for other unusual situations, so it certainly won't have hurt to make.

We'll be pushing a new update to CurseForge once we can test a number of other fixes that have recently been made.

**Comment by NielsPilgaard** [comment]
Awesome, thank you!

**Comment by Won-Ton** [comment]
Just to clear up:

During worldgen, structures/features are given a `WorldGenRegion` as the `IWorld` implementation to operate on - casting that to a concrete `World`/`ServerWorld` will always throw the ClassCastException. This isn't a mod compatibility issue it's just a bug; you'd have this problem in vanilla under the right circumstances.

(Aside: TF _does_ wrap that region, but the wrapper itself extends `WorldGenRegion` so anybody downstream can still safely cast to that if needed)

**Comment by Vaelzan** [comment]
Fixed in the 0.1.3 release on CurseForge.
