### ISSUE TITLE
Valhelsia Structures has failed to load correctly

### ISSUE THREAD

**Issue by rexyev** [stal111/Valhelsia-Structures#89]
![prof](https://user-images.githubusercontent.com/87056978/124704291-b061bf00-dea8-11eb-8a93-397f53e8dbca.PNG)
Does anybody know how to fix this please?

**Comment by TheRanker** [comment]
Will need a  latest.log from ur /logs/ folder.

**Comment by Vaelzan** [comment]
> ![prof](https://user-images.githubusercontent.com/87056978/124704291-b061bf00-dea8-11eb-8a93-397f53e8dbca.PNG)
> Does anybody know how to fix this please?

That error is caused by a problem with the config file. The easiest way to fix it is to delete the config for Valhelsia Structures (valhelsia_structures-common.toml) and launch the game again, although you may also have the same issue with other mods (since it's common for several mods to end up with corrupted configs at the same time).
